/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'text' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface Notification {
  'seen' : boolean,
  'recipient' : Principal,
  'timestamp' : bigint,
  'eventType' : NotificationEventType,
  'postId' : [] | [bigint],
}
export type NotificationEventType = { 'userFollowed' : null } |
  { 'postLiked' : null } |
  { 'postCommented' : null };
export interface Post {
  'id' : bigint,
  'likeCount' : bigint,
  'author' : Principal,
  'imageUrl' : string,
  'timestamp' : bigint,
  'caption' : string,
  'comments' : Array<Comment>,
}
export interface Story {
  'author' : Principal,
  'imageUrl' : string,
  'timestamp' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string, string], undefined>,
  'createStory' : ActorMethod<[string], undefined>,
  'follow' : ActorMethod<[Principal], undefined>,
  'getActiveStories' : ActorMethod<[], Array<[Principal, Array<Story>]>>,
  'getAllPostsForExplore' : ActorMethod<[], Array<Post>>,
  'getAllRecentPosts' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFollowerCount' : ActorMethod<[Principal], bigint>,
  'getFollowingCount' : ActorMethod<[Principal], bigint>,
  'getHomeFeed' : ActorMethod<[], Array<Post>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getSavedPosts' : ActorMethod<[], Array<Post>>,
  'getStoryAvatars' : ActorMethod<[], Array<[Principal, string]>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasLikedPost' : ActorMethod<[bigint], boolean>,
  'hasSavedPost' : ActorMethod<[bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePost' : ActorMethod<[bigint], undefined>,
  'searchUsers' : ActorMethod<[string], Array<[Principal, UserProfile]>>,
  'unfollow' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'unsavePost' : ActorMethod<[bigint], undefined>,
  'updateProfile' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];