/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Story = IDL.Record({
  'author' : IDL.Principal,
  'imageUrl' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Comment = IDL.Record({
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'author' : IDL.Principal,
  'imageUrl' : IDL.Text,
  'timestamp' : IDL.Int,
  'caption' : IDL.Text,
  'comments' : IDL.Vec(Comment),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const NotificationEventType = IDL.Variant({
  'userFollowed' : IDL.Null,
  'postLiked' : IDL.Null,
  'postCommented' : IDL.Null,
});
export const Notification = IDL.Record({
  'seen' : IDL.Bool,
  'recipient' : IDL.Principal,
  'timestamp' : IDL.Int,
  'eventType' : NotificationEventType,
  'postId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createStory' : IDL.Func([IDL.Text], [], []),
  'follow' : IDL.Func([IDL.Principal], [], []),
  'getActiveStories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Story)))],
      ['query'],
    ),
  'getAllPostsForExplore' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllRecentPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getHomeFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getSavedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getStoryAvatars' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasLikedPost' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'hasSavedPost' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'markNotificationsRead' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePost' : IDL.Func([IDL.Nat], [], []),
  'searchUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'unfollow' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'unsavePost' : IDL.Func([IDL.Nat], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Story = IDL.Record({
    'author' : IDL.Principal,
    'imageUrl' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Comment = IDL.Record({
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'author' : IDL.Principal,
    'imageUrl' : IDL.Text,
    'timestamp' : IDL.Int,
    'caption' : IDL.Text,
    'comments' : IDL.Vec(Comment),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const NotificationEventType = IDL.Variant({
    'userFollowed' : IDL.Null,
    'postLiked' : IDL.Null,
    'postCommented' : IDL.Null,
  });
  const Notification = IDL.Record({
    'seen' : IDL.Bool,
    'recipient' : IDL.Principal,
    'timestamp' : IDL.Int,
    'eventType' : NotificationEventType,
    'postId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createStory' : IDL.Func([IDL.Text], [], []),
    'follow' : IDL.Func([IDL.Principal], [], []),
    'getActiveStories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Story)))],
        ['query'],
      ),
    'getAllPostsForExplore' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllRecentPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getHomeFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getSavedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getStoryAvatars' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasLikedPost' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'hasSavedPost' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'markNotificationsRead' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePost' : IDL.Func([IDL.Nat], [], []),
    'searchUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'unfollow' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'unsavePost' : IDL.Func([IDL.Nat], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };